import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity, Bell, CheckCircle2, CircleAlert, FileText, LayoutDashboard, LogOut, Menu, RefreshCw, Users, Workflow as WorkflowIcon, XCircle} from 'lucide-react'
import './styles.css'

const columns=[['TODO','待处理'],['ASSIGNED','已分配'],['IN_PROGRESS','开发中'],['BLOCKED','阻塞'],['DELIVERY_SUBMITTED','待交付'],['CI_RUNNING','CI 中'],['DONE','已完成'],['CANCELLED_OR_FAILED','已取消/失败']]
const api=async(path,opts={})=>{const token=localStorage.getItem('ac_token');const r=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(r.status===401)throw Error('登录已过期');if(!r.ok){let m=`请求失败 (${r.status})`;try{m=(await r.json()).message||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
const stateLabel=s=>({CI_NOT_CONFIGURED:'未配置',CI_REQUIRED:'已启用门禁',TODO:'待处理',ASSIGNED:'已分配',IN_PROGRESS:'开发中',BLOCKED:'阻塞',DELIVERY_SUBMITTED:'待交付',CI_RUNNING:'CI 中',DONE:'已完成',CANCELLED:'已取消',FAILED:'失败',CURRENT:'当前',STALE:'已过期'}[s]||s||'未知')
const tone=s=>/DONE|PASSED|CURRENT|SUCCEEDED/.test(s)?'good':/BLOCKED|FAILED|CANCELLED|STALE/.test(s)?'bad':/RUNNING|ASSIGNED|SUBMITTED|PROPOSED/.test(s)?'info':'neutral'
function Status({value}){return <span className={`status ${tone(value)}`}>{/DONE|PASSED|SUCCEEDED/.test(value)?<CheckCircle2 size={13}/>:/BLOCKED|FAILED|CANCELLED/.test(value)?<CircleAlert size={13}/>:<Activity size={13}/>} {stateLabel(value)}</span>}
function Login({onLogin}){const [mode,setMode]=useState('login');const [form,setForm]=useState({username:'',password:''});const [error,setError]=useState('');const register=mode==='register';const submit=async e=>{e.preventDefault();setError('');try{const path=register?'/api/auth/register':'/api/auth/login';const r=await api(path,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('ac_token',r.accessToken);onLogin(r)}catch(x){setError(x.message)}};return <main className="login"><form onSubmit={submit} className="login-card"><div className="logo">AC</div><p className="kicker">工程协作平台</p><h1>{register?'创建账号':'登录工作台'}</h1><label>用户名<input required minLength={register?3:1} maxLength={50} autoComplete="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>密码<input required minLength={register?8:1} maxLength={128} type="password" autoComplete={register?'new-password':'current-password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="primary wide">{register?'注册并进入':'登录'}</button>{error&&<p className="error">{error}</p>}<button type="button" className="auth-switch" onClick={()=>{setMode(register?'login':'register');setError('')}}>{register?'已有账号？返回登录':'没有账号？注册'}</button></form></main>}
function App(){const [user,setUser]=useState(null);const [projects,setProjects]=useState([]);const [project,setProject]=useState(null);const [workflows,setWorkflows]=useState([]);const [page,setPage]=useState('overview');const [mobile,setMobile]=useState(false);const [error,setError]=useState('');useEffect(()=>{if(localStorage.getItem('ac_token'))load()},[]);async function load(){try{const [ps,ws]=await Promise.all([api('/api/projects'),api('/api/workflows')]);const projectList=Array.isArray(ps)?ps:[];const workflowList=Array.isArray(ws)?ws:[];setProjects(projectList);setProject(p=>p&&projectList.some(item=>item.id===p.id)?p:(projectList[0]||null));setWorkflows(workflowList);setUser(current=>current||{username:'当前用户'});setError('')}catch(e){setError(e.message);if(e.message.includes('过期'))logout()}}function logout(){localStorage.removeItem('ac_token');setUser(null)}useEffect(()=>{if(user)load()},[page]);if(!user)return <Login onLogin={r=>{setUser({username:r.username});load()}}/>;const nav=[['overview','项目概览',LayoutDashboard],['workflows','工作流',WorkflowIcon],['board','任务看板',LayoutDashboard],['members','项目成员',Users],['notifications','通知',Bell],['audit','审计日志',FileText]];return <div className="shell"><header className="top"><button className="icon mobile" onClick={()=>setMobile(!mobile)} aria-label="打开导航"><Menu size={20}/></button><strong className="brand">Agent Collaborate</strong><span className="heading">{nav.find(n=>n[0]===page)?.[1]}</span><select value={project?.id||''} onChange={e=>setProject(projects.find(p=>String(p.id)===e.target.value))}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="icon" onClick={load} aria-label="刷新"><RefreshCw size={17}/></button><button className="user" onClick={logout}><LogOut size={15}/>{user.username}</button></header><aside className={`side ${mobile?'open':''}`}><nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>{setPage(key);setMobile(false)}}><Icon size={17}/><span>{label}</span></button>)}</nav><footer>状态以服务端事实为准<br/><small>MVP 管理工作台</small></footer></aside><main className="content">{error&&<div className="alert"><CircleAlert size={16}/>{error}<button className="icon" onClick={()=>setError('')}><XCircle size={15}/></button></div>}{page==='overview'&&<Overview project={project} workflows={workflows}/>} {page==='workflows'&&<Workflows workflows={workflows} onBoard={()=>setPage('board')}/>} {page==='board'&&<Board workflows={workflows}/>} {page==='members'&&<Members project={project}/>} {page==='notifications'&&<Notifications/>} {page==='audit'&&<Audit project={project}/>}</main></div>}
function Overview({project,workflows}){const active=workflows.filter(w=>!['DONE','CANCELLED','FAILED'].includes(w.status));return <><div className="page-head"><div><h1>{project?.name||'项目概览'}</h1><p>{project?.repositoryUrl||'请选择项目'}</p></div><Status value={project?.ciStatus}/></div><div className="metrics"><Metric label="进行中 Workflow" value={active.length}/><Metric label="项目 CI" value={stateLabel(project?.ciStatus)}/><Metric label="阻塞任务" value="--"/><Metric label="最近同步" value="--"/></div><section className="panel"><h2>当前工作流</h2>{active.length?active.map(w=><div className="list-row" key={w.id}><div><strong>{w.title}</strong><small>{w.intentLevel} · {w.completionMode}</small></div><Status value={w.status}/></div>):<Empty text="暂无进行中的 Workflow"/>}</section></>}
function Metric({label,value}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function Workflows({workflows,onBoard}){return <><div className="page-head"><div><h1>工作流</h1><p>意图、文档版本和交付状态</p></div></div><section className="panel">{workflows.length?workflows.map(w=><div className="list-row" key={w.id}><div><strong>{w.title}</strong><small>{w.intentLevel} · {w.description}</small></div><Status value={w.status}/><button className="button" onClick={onBoard}>看板</button></div>):<Empty text="暂无 Workflow"/>}</section></>}
function Board({workflows}){const [data,setData]=useState(null);const wf=workflows[0];useEffect(()=>{if(wf)api(`/api/workflows/${wf.id}/board`).then(setData).catch(()=>{})},[wf?.id]);const groups=useMemo(()=>Object.fromEntries((data?.columns||[]).map(c=>[c.key,c.cards])),[data]);return <><div className="page-head"><div><h1>任务看板</h1><p>只读聚合 · 看板不直接修改状态</p></div></div><div className="board-scroll"><div className="board">{columns.map(([key,label])=><section className="column" key={key}><h3>{label}<b>{(groups[key]||[]).length}</b></h3>{(groups[key]||[]).map(t=><article className="task" key={t.id}><strong>{t.externalKey||t.taskKey} · {t.title}</strong><Status value={t.status}/><small>负责人：{t.assignee?.username||'未分配'}</small><small>任务包 v{t.currentPackageVersion||'-'} · {t.branchName||'无分支'}</small><small>CI：{t.ciStatus||'--'} · {t.updatedAt||'--'}</small></article>)}{!(groups[key]||[]).length&&<Empty text="暂无任务"/>}</section>)}</div></div></>}
function Members({project}){const [items,setItems]=useState([]);const [error,setError]=useState('');useEffect(()=>{setError('');setItems([]);if(project)api(`/api/projects/${project.id}/members`).then(r=>setItems(Array.isArray(r)?r:[])).catch(e=>setError(e.message))},[project?.id]);return <><div className="page-head"><div><h1>项目成员</h1><p>角色与能力画像</p></div></div><section className="panel">{!project?<Empty text="暂无项目，请先创建项目"/>:error?<Empty text={`无法加载项目成员：${error}`}/>:items.length?items.map(m=><div className="list-row" key={m.id}><div><strong>{m.username||'未命名用户'}</strong><small>{m.projectRole||'未知角色'} · 画像 v{m.profileVersion??'-'}</small></div><Status value={m.profileCompleted?'CURRENT':'PENDING'}/></div>):<Empty text="该项目暂无成员"/>}</section></>}
function Notifications(){const [items,setItems]=useState([]);const refresh=()=>api('/api/notifications').then(setItems).catch(()=>{});useEffect(refresh,[]);return <><div className="page-head"><div><h1>通知</h1><p>当前用户的任务、阻塞和交付提醒</p></div></div><section className="panel">{items.length?items.map(n=><div className={`list-row ${n.readAt?'':'unread'}`} key={n.id}><div><strong>{n.title}</strong><small>{n.content} · {n.createdAt}</small></div>{n.readAt?<Status value="CURRENT"/>:<button className="button" onClick={()=>api(`/api/notifications/${n.id}/read`,{method:'POST'}).then(refresh)}>标记已读</button>}</div>):<Empty text="暂无通知"/>}</section></>}
function Audit({project}){const [items,setItems]=useState([]);const [error,setError]=useState('');useEffect(()=>{setError('');setItems([]);if(project)api(`/api/audit-logs?projectId=${project.id}&page=0&size=50`).then(r=>setItems(Array.isArray(r)?r:(Array.isArray(r?.content)?r.content:[]))).catch(e=>setError(e.message))},[project?.id]);return <><div className="page-head"><div><h1>审计日志</h1><p>项目级时间线，按最新时间排序</p></div></div><section className="panel">{!project?<Empty text="暂无项目，创建项目后可查看审计日志"/>:error?<Empty text={`无法加载审计日志：${error}`}/>:items.length?items.map(a=><div className="audit" key={a.id}><time>{a.createdAt?new Date(a.createdAt).toLocaleString():'时间未知'}</time><div><strong>{a.action||'未知操作'} · {a.entityType||'未知实体'} #{a.entityId??'-'}</strong><small>操作人：{a.actorUserId||'系统'}</small></div></div>):<Empty text="暂无审计记录"/>}</section></>}
function Empty({text}){return <div className="empty">{text}</div>}
class AppErrorBoundary extends React.Component{constructor(props){super(props);this.state={error:null}}static getDerivedStateFromError(error){return {error}}componentDidCatch(error){console.error('前端页面渲染失败',error)}render(){return this.state.error?<main className="login"><section className="login-card"><div className="logo">AC</div><h1>页面暂时无法显示</h1><p className="error">请刷新页面后重试。</p><button className="primary wide" onClick={()=>location.reload()}>刷新页面</button></section></main>:this.props.children}}
createRoot(document.getElementById('root')).render(<AppErrorBoundary><App/></AppErrorBoundary>)
